### PR TITLE
Added Inventory Routes for client app

### PR DESCRIPTION
**Pull request by dfodeker**

### CODE REVIEW

**Comment by dfodeker** [comment]
this PR allows us view the inventory updates of each product through the client app since we no longer have the bulk reporting workflow

**Comment by dfodeker** [comment]
added Route /inventory/:store: and Route /inventory/:store:/:filename:
🛠️💥🎉

**Review by robertbfxr — APPROVED** [review]
As far as I can tell, looks good :)

**Comment by dfodeker** [comment]
Thanks Rob!

**Pull request merged**
